[build]
builder = "nixpacks"
buildCommand = "npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend"

[deploy]
startCommand = "node backend/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
